Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2019-11, with the labels that each got.

#536 Document classes in data package
  data/__init__.py
  data/nemo.py
  data/netcdf_data.py
  data/utils.py
  data/variable_list.py
Labels: Documentation, Python

#537 Changed Sound Calc Names to add deep
  oceannavigator/datasetconfig.json
Labels: Erica Wishlist, enhancement

#538 Modify tests
  data/calculated_parser/functions.py
  tests/test_functions.py
Labels: Python, enhancement, technical

#542 Colormap_diff Fix
  oceannavigator/frontend/src/components/AreaWindow.jsx
  plotting/map.py
Labels: Bugfix, Erica Wishlist, Javascript, Priority: High, Python

#544 Fix virtual mooring crash
  plotting/timeseries.py
Labels: Bugfix, Python

#539 Improved Sub-Surface Channel Detection
  data/calculated_parser/functions.py
  oceannavigator/datasetconfig.json
  routes/routes_impl.py
  tests/test_functions.py
Labels: Erica Wishlist, Python, enhancement

#557 fixed colourmap url
  oceannavigator/frontend/src/components/AreaWindow.jsx
Labels: Bugfix, Erica Wishlist, Javascript

#559 Fix loading of Mercator datasets
  data/__init__.py
  data/mercator.py
  data/sqlite_database.py
  tests/test_sqlite_database.py
Labels: Bugfix, Python
