Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2019-12, with the labels that each got.

#573 datasetconfig.json fix
  oceannavigator/datasetconfig.json
Labels: Bugfix, Data/Pipelines, Priority: High

#574 Updated UI Version Number
  oceannavigator/frontend/src/components/LayerSelection.jsx
Labels: Documentation, Javascript

#576 test hotfix
  data/calculated_parser/parser.py
Labels: Bug, Bugfix, Priority: High, Python

#581 Ui scroll fix
  oceannavigator/frontend/src/stylesheets/components/_Map.scss
Labels: Bugfix, Javascript, Priority: Medium

#591 Multi point fix
  oceannavigator/frontend/src/components/Map.jsx
Labels: Bugfix, Javascript, Priority: Medium

#584 Scale bar align fix
  oceannavigator/frontend/src/components/Layer.jsx
Labels: Bugfix, Javascript, Priority: Medium

#593 Feature selection
  oceannavigator/frontend/src/components/Map.jsx
Labels: Bugfix, Javascript, Priority: Low, Priority: Medium

#596 Colourmaps
  plotting/colormap.py
Labels: Bugfix, Priority: High, Python, User Requested

#569 Calculation Vectorization
  data/calculated_parser/functions.py
  oceannavigator/datasetconfig.json
Labels: Performance, Python, enhancement

#595 French translation
  oceannavigator/frontend/src/components/ContactButton.jsx
  oceannavigator/frontend/src/components/Contacts.jsx
  oceannavigator/frontend/src/components/CoordInputPanel.jsx
  oceannavigator/frontend/src/components/FeatureSelection.jsx
  oceannavigator/frontend/src/components/Foundation_Maps.jsx
  oceannavigator/frontend/src/components/Layer.jsx
  oceannavigator/frontend/src/components/LayerRearrange.jsx
  oceannavigator/frontend/src/components/LayerSelection.jsx
  oceannavigator/frontend/src/components/LayerWrap.jsx
  oceannavigator/frontend/src/components/LineWindow.jsx
  oceannavigator/frontend/src/components/MapToolbar.jsx
  oceannavigator/frontend/src/components/ModalContainer.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
  oceannavigator/frontend/src/components/WarningBar.jsx
  oceannavigator/frontend/src/components/time/TimePicker.jsx
Labels: Javascript, Priority: High, enhancement

#594 Datasetconfig
  data/calculated_parser/functions.py
  oceannavigator/datasetconfig.json
Labels: Bugfix, Priority: High, Python

#600 Layer component will only set enabled datasets
  oceannavigator/frontend/src/components/Layer.jsx
Labels: Bugfix, Javascript, Priority: High

#602 Add check for depth dimension in get_profile
  data/mercator.py
  data/nemo.py
Labels: Python, enhancement

#604 removed duplicate variable
  oceannavigator/datasetconfig.json
Labels: Bugfix, Priority: High

#605 Makes the Cookie disclaimer smaller
  oceannavigator/frontend/src/components/LayerSelection.jsx
Labels: Bugfix, Javascript, enhancement
