Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2019-07, with the labels that each got.

#457 Add Jinshan scripts
  scripts/readNovaFloat_SN472.py
  scripts/usingFloat2extracCls4.py
Labels: Python

#460 Updated translations
  messages.pot
  oceannavigator/translations/en.json
  oceannavigator/translations/en/LC_MESSAGES/messages.po
  oceannavigator/translations/fr.json
  oceannavigator/translations/fr/LC_MESSAGES/messages.po
Labels: enhancement

#466 Conda fix
  config/conda/environment.yml
Labels: Bugfix, Python

#467 Drifter plot fix (environment update)
  config/conda/environment.yml
Labels: Bugfix, Python
