Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2019-06, with the labels that each got.

#436 netcdftime is now cftime
  data/mercator.py
  data/netcdf_data.py
  plotting/drifter.py
  plotting/grid.py
  plotting/observation.py
  utils/misc.py
Labels: Python

#440 Python Environment update
  config/conda/environment.yml
  utils/misc.py
Labels: Backend, Python

#441 Small refactor
  data/mercator.py
  data/netcdf_data.py
  plotting/hovmoller.py
  plotting/utils.py
  tests/test_merc.py
  tests/test_nemo.py
Labels: Python, technical

#442 Conda Environment update
  config/conda/environment.yml
Labels: Python, enhancement, technical

#450 Update React and OpenLayers
  oceannavigator/frontend/package-lock.json
  oceannavigator/frontend/package.json
  oceannavigator/frontend/src/components/Map.jsx
Labels: Javascript

#453 Make link customization panel expanded by default
  oceannavigator/frontend/src/components/Permalink.jsx
Labels: Javascript, enhancement
