Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2019-10, with the labels that each got.

#503 corrected bug in temperature/salinity reversal in calls to sspeed calculation
  oceannavigator/datasetconfig.json
  tests/test_data_utils.py
Labels: Bugfix, Priority: Medium, Python

#506 Implement `magnitude` calculation function
  data/calculated_parser/functions.py
  oceannavigator/datasetconfig.json
  plotting/point.py
  plotting/scale.py
  plotting/stick.py
Labels: Bugfix, Python

#510 Sound Channel Calculations
  data/calculated.py
  data/calculated_parser/functions.py
  data/calculated_parser/lexer.py
  data/calculated_parser/parser.out
  data/calculated_parser/parser.py
  data/calculated_parser/parsetab.py
  data/nemo.py
  oceannavigator/datasetconfig.json
  oceannavigator/frontend/src/components/PlotImage.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
  plotting/colormap.py
  plotting/sound.py
  plotting/tile.py
Labels: Erica Wishlist, Python, User Requested, enhancement

#519 Fix virtual mooring
  data/data.py
  data/netcdf_data.py
  oceannavigator/frontend/src/components/PointWindow.jsx
  plotting/timeseries.py
Labels: Bugfix, Javascript, Python
