Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2019-05, with the labels that each got.

#419 Fix some vulnerabilities
  oceannavigator/frontend/package-lock.json
  oceannavigator/frontend/package.json
Labels: Javascript

#424 eslint auto-fixes
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/ComboBox.jsx
  oceannavigator/frontend/src/components/CoordInputPanel.jsx
  oceannavigator/frontend/src/components/DrifterSelector.jsx
  oceannavigator/frontend/src/components/EnterLine.jsx
  oceannavigator/frontend/src/components/Map.jsx
  oceannavigator/frontend/src/components/MapToolbar.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/Options.jsx
  oceannavigator/frontend/src/components/Permalink.jsx
  oceannavigator/frontend/src/components/Range.jsx
  oceannavigator/frontend/src/components/TimePicker.jsx
  oceannavigator/frontend/src/i18n.js
  oceannavigator/frontend/src/index.jsx
Labels: Javascript

#429 Update datasetconfig.json
  oceannavigator/datasetconfig.json
Labels: Backend, enhancement

#433 Workaround for subset failure
  data/netcdf_data.py
Labels: Bugfix, Python

#434 Lat / Lon variable fix for subsetting
  data/netcdf_data.py
Labels: Bugfix, Python
