Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2020-04, with the labels that each got.

#708 Fix data.class4.list_class4_models crash
  data/class4.py
  tests/test_api_v_1_0.py
Labels: Bugfix, Code Quality, Python

#710 Water velocity magnitudes for historical giops
  oceannavigator/datasetconfig.json
Labels: Bugfix, Data/Pipelines

#706 Observational Data Importers
  scripts/data_importers/argo.py
  scripts/data_importers/concepts_drifter.py
  scripts/data_importers/glider.py
  scripts/data_importers/nafc_ctd.py
  scripts/data_importers/seal.py
Labels: New Feature, Python

#711 Speed up time_index_to_datetime()
  data/utils.py
Labels: Performance, Python

#709 Add SalishSeaCast currents dataset config, colour maps & dataset handling
  data/calculated_parser/functions.py
  data/netcdf_data.py
  oceannavigator/dataset_config.py
  oceannavigator/datasetconfig.json
  plotting/colormap.py
  routes/api_v1_0.py
  tests/test_netcdf_data.py
  tests/testdata/datasetconfigpatch.json
  tests/testdata/grid_angle_salishsea_201702.nc
Labels: Data/Pipelines, Python, enhancement

#714 Fix bottom timeseries data for Mercator & Nemo
  data/mercator.py
  data/nemo.py
  tests/test_api_v_1_0.py
  tests/testdata/endpoints.json
Labels: Bugfix, Python

#707 Observational UI
  data/model.py
  data/observational/queries.py
  oceannavigator/frontend/package.json
  oceannavigator/frontend/src/components/Map.jsx
  oceannavigator/frontend/src/components/MapToolbar.jsx
  oceannavigator/frontend/src/components/ObservationSelector.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/PlotImage.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
  oceannavigator/frontend/src/components/TrackWindow.jsx
  oceannavigator/frontend/src/stylesheets/components/_Map.scss
  oceannavigator/frontend/src/stylesheets/components/_ObservationSelector.scss
  oceannavigator/frontend/src/stylesheets/components/_input.scss
  plotting/drifter.py
  plotting/observation.py
  plotting/track.py
  plotting/transect.py
  plotting/utils.py
  routes/api_v1_0.py
Labels: Javascript, New Feature, Python

#719 Cleanup
  routes/api_v1_0.py
  tests/test_api_v_1_0.py
  utils/misc.py
Labels: Code Quality, Python

#715 Fix quiver plot + driveby code quality improvement
  plotting/map.py
  plotting/plotter.py
Labels: Bugfix, Code Quality, Python

#720 Subset + Scriptgen fix
  oceannavigator/datasetconfig.json
  plotting/templates/pythonSUBSETtemplate.txt
Labels: Bugfix, Python

#725 Add warning banner
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/WarningBar.jsx
Labels: Javascript, User Requested

#724 Quick and dirty clean up of R script generation.
  data/calculated_parser/__init__.py
  plotting/scriptGenerator.py
  plotting/templates/pythonPLOTtemplate.txt
  plotting/templates/rPLOTtemplate.txt
Labels: Bugfix, Code Quality, Python

#726 Implement Deep Sound Channel Bottom calculated variable
  data/calculated_parser/functions.py
  oceannavigator/datasetconfig.json
Labels: Erica Wishlist, New Feature, Python, User Requested
