Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2020-02, with the labels that each got.

#635 Add BIORYS Global Monthly + Daily Datasets
  oceannavigator/datasetconfig.json
  plotting/colormap.py
Labels: Data/Pipelines, enhancement

#634 Fix deprecated uses of @abc.abstractproperty
  data/data.py
Labels: Code Quality, Python, technical

#638 Add port of St John and Bay of Fundy datasets
  oceannavigator/datasetconfig.json
Labels: Data/Pipelines, User Requested

#639 Added missing import
  utils/misc.py
Labels: Bugfix, Python

#640 Fix duplicate timestamps returned from database
  data/sqlite_database.py
Labels: Bugfix, Python

#642 Extend calculation layer to support full-depth slicing
  data/calculated.py
  data/calculated_parser/lexer.py
  data/calculated_parser/parser.py
  tests/test_calculated_data.py
  tests/test_calculated_parser.py
Labels: Python, enhancement, technical

#643 Add Deep Sound Channel calculated variable
  data/calculated_parser/functions.py
  oceannavigator/datasetconfig.json
  plotting/colormap.py
  tests/test_data_functions.py
Labels: Data/Pipelines, Erica Wishlist, Python, User Requested, enhancement

#644 Add MyOcean Arctic Datasets
  oceannavigator/datasetconfig.json
Labels: Data/Pipelines, enhancement

#645 Add CMEMS Arctic Reanalysis
  oceannavigator/datasetconfig.json
Labels: Data/Pipelines

#647 Fix vector_variables property in DatasetConfig class.
  oceannavigator/dataset_config.py
  tests/test_dataset_config.py
Labels: Bugfix, Python

#648 Deprecate vectors api argument
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
  routes/api_v1_0.py
  tests/test_api_v_1_0.py
Labels: Code Quality, Javascript, Python, technical

#651 Add 10-day forecasts
  oceannavigator/datasetconfig.json
Labels: Data/Pipelines, User Requested, enhancement

#654 Remove unused attributes in mercator.py
  data/mercator.py
Labels: Bugfix, Python

#656 Cast time dim values to int when calculating corresponding time index
  data/netcdf_data.py
Labels: Bugfix, Python, technical

#657 API cleanup and testing
  oceannavigator/__init__.py
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/Class4Window.jsx
  oceannavigator/frontend/src/components/ContourSelector.jsx
  oceannavigator/frontend/src/components/DrifterSelector.jsx
  oceannavigator/frontend/src/components/DrifterWindow.jsx
  oceannavigator/frontend/src/components/Map.jsx
  oceannavigator/frontend/src/components/MapToolbar.jsx
  oceannavigator/frontend/src/components/ObservationSelector.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
  oceannavigator/frontend/src/components/QuiverSelector.jsx
  oceannavigator/frontend/src/components/StatsTable.jsx
  plotting/scriptGenerator.py
  plotting/templates/pythonPLOTtemplate.txt
  routes/api_v0_0.py
  routes/api_v1_0.py
  routes/routes_impl.py
  tests/test_api_v_1_0.py
  tests/testdata/datasetconfigpatch.json
  tests/testdata/endpoints.json
  tests/testdata/giops_test.nc
Labels: Code Quality, Python, technical

#659 Add Vancouver Ferry Routes KML
  kml/line/Vancouver Ferry Routes.kml
Labels: User Requested, enhancement

#660 Add Nitrogen and Oxygen Solubility calculated variables
  data/calculated_parser/functions.py
  oceannavigator/datasetconfig.json
  plotting/colormap.py
Labels: Python, enhancement

#665 Update MPAs KML
  kml/area/DFO_MPA_2019_08_01.kml
  kml/area/MPAs.kml
Labels: User Requested, enhancement

#667 Front-end: display hours in UTC
  oceannavigator/frontend/src/components/TimePicker.jsx
Labels: Bugfix, Javascript

#666 Increase Max Zoom
  oceannavigator/frontend/src/components/Map.jsx
  routes/api_v1_0.py
Labels: Javascript, Python, User Requested

#662 Update dataset config
  oceannavigator/datasetconfig.json
Labels: Data/Pipelines, User Requested

#669 Implement sonic layer depth calculated variable
  data/calculated_parser/functions.py
  oceannavigator/datasetconfig.json
  tests/test_data_functions.py
Labels: Erica Wishlist, Python, User Requested, enhancement

#668 Change shebang
  scripts/generate_class4_list.py
Labels: Code Quality, Python, technical
