Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2020-01, with the labels that each got.

#614 Implement LRU cache for open_dataset
  data/__init__.py
  tests/test_data_open_dataset.py
  utils/decorators.py
Labels: Performance, Python, enhancement, technical

#613 Changed default dataset ID
  oceannavigator/frontend/src/components/Layer.jsx
Labels: Bugfix, Javascript, Priority: High

#615 Pare down datasetconfig
  oceannavigator/datasetconfig.json
Labels: Priority: High

#621 CLASS4: Replace thredds indexing with FTP indexing
  data/class4.py
  oceannavigator/oceannavigator.cfg
  plotting/class4.py
  scripts/generate_class4_list.py
Labels: Bugfix, Priority: Medium, Python, technical

#626 Various capitalization mistakes
  oceannavigator/oceannavigator.cfg
Labels: Bugfix, Priority: High

#627 Implement CORS
  routes/api_v1_0.py
Labels: Python, technical

#628 Add test class for calculated functions
  tests/test_data_functions.py
Labels: Code Quality, Python, technical

#629 Raise SyntaxError when p_error is called
  data/calculated_parser/parser.py
  tests/test_calculated_parser.py
Labels: Bugfix, Python

#630 Change shape of CalculatedArray to consider user-defined dims
  data/calculated.py
  oceannavigator/datasetconfig.json
  tests/test_calculated_data.py
Labels: Python, technical

#632 Add Density, Heat Capacity, Temp Gradient variables
  data/calculated_parser/functions.py
  oceannavigator/datasetconfig.json
  plotting/colormap.py
Labels: Data/Pipelines, Python, enhancement

#633 Add CMEMS Global Monthly
  oceannavigator/datasetconfig.json
Labels: Data/Pipelines, enhancement
