Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2020-11, with the labels that each got.

#774 Fix ValueError due to 1D lons/lats in subset API call
  data/netcdf_data.py
  tests/test_netcdf_data.py
  tests/testdata/datasetconfigpatch.json
Labels: Bug, Priority: High, Python

#768 Image Optimization removed
  plotting/plotter.py
Labels: Python, technical

#775 Change showmap default to false for Points & Class4 UI overlays
  oceannavigator/frontend/src/components/Class4Window.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
Labels: Javascript, Performance, Priority: High

#780 Fix ValueError due to "dimensions do not exist" in subset API call
  data/netcdf_data.py
  tests/test_netcdf_data.py
Labels: Bug, Priority: High, Python

#776 Add Sentry integration for backend via Flask app
  oceannavigator/__init__.py
  routes/api_v1_0.py
Labels: Infrastructure - LXC, New Feature, Python, dependencies, technical

#788 Add possible Sentry environment name from envvar
  oceannavigator/__init__.py
Labels: Python, enhancement, technical
