Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2020-07, with the labels that each got.

#736 Admin cleaning and script tuning
  README.md
  bin/launch-web-service.sh
  bin/runserver.py
  bin/runserver.sh
Labels: Infrastructure - LXC, enhancement

#739 Set default [...]/oceannavigator/configs to use the off-site branch
  .gitmodules
Labels: enhancement

#742 Adding in symbolic links to certain bin files and added in an update …
  bin/launch-pickle.sh
  oceannavigator/frontend/package.json
Labels: Documentation, dependencies, enhancement

#741 Update to the information available to end users
  launch-web-service.sh
  oceannavigator/frontend/data-help/cmems-GLOBAL_REANALYSIS_PHY_001_030.html
  oceannavigator/frontend/data-help/freebiorys2v4_monthly.html
  oceannavigator/frontend/data-help/giops-10day.html
  oceannavigator/frontend/data-help/giops-day.html
  oceannavigator/frontend/data-help/giops.html
  oceannavigator/frontend/data-help/glorys12_climatology_monthly.html
  oceannavigator/frontend/data-help/glorys12_climatology_seasonal.html
  oceannavigator/frontend/data-help/riops.html
  oceannavigator/frontend/data-help/salishseacast_2d_ssh.html
  oceannavigator/frontend/data-help/salishseacast_3d_biology.html
  oceannavigator/frontend/data-help/salishseacast_3d_currents.html
  oceannavigator/frontend/data-help/salishseacast_3d_tracers.html
  oceannavigator/frontend/data-help/wcps.html
  runserver.py
  runserver.sh
Labels: enhancement

#743 Add helper script to run python tests
  .github/pull_request_template.md
  run_python_tests.sh
Labels: technical

#744 Add more unit tests
  data/netcdf_data.py
  tests/test_create_app.py
  tests/test_merc.py
  tests/test_nemo.py
  tests/test_netcdf_data.py
  tests/test_variable.py
Labels: Python, technical

#745 Fix crash when requesting a CSV for maps
  plotting/map.py
  plotting/utils.py
  tests/test_api_v_1_0.py
  tests/testdata/endpoints.json
Labels: Bugfix, Python
