Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2020-03, with the labels that each got.

#670 Added a new script to daemonize runserver.sh. Tweaked oceannavigator.…
  launch-web-service.sh
  oceannavigator/oceannavigator.cfg
Labels: Backend, technical

#671 Upgrade React-Bootsrap to 0.33.1
  oceannavigator/frontend/package.json
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/Class4Window.jsx
  oceannavigator/frontend/src/components/ComboBox.jsx
  oceannavigator/frontend/src/components/CoordInputPanel.jsx
  oceannavigator/frontend/src/components/LineWindow.jsx
  oceannavigator/frontend/src/components/MapInputs.jsx
  oceannavigator/frontend/src/components/Options.jsx
  oceannavigator/frontend/src/components/Permalink.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
Labels: Javascript, enhancement, technical

#677 use /usr/bin/env python as per style guide
  runserver.py
Labels: Code Quality, Python

#672 GPSC modifications
  launch-web-service.sh
  runserver.sh
Labels: Backend, technical

#641 Refactor open_dataset() for inversion of control & factory architecture
  data/__init__.py
  data/calculated.py
  data/data.py
  data/fvcom.py
  data/mercator.py
  data/model.py
  data/nemo.py
  data/netcdf_data.py
  plotting/hovmoller.py
  plotting/map.py
  plotting/profile.py
  plotting/timeseries.py
  plotting/transect.py
  plotting/ts.py
  routes/api_v1_0.py
  tests/test_api_v_1_0.py
  tests/test_calculated_data.py
  tests/test_data_open_dataset.py
  tests/test_merc.py
  tests/test_nemo.py
  tests/test_netcdf_data.py
  tests/testdata/datasetconfigpatch.json
  tests/testdata/salishseacast_ssh_test.nc
Labels: Python, enhancement, technical

#681 Update to the runserver.sh script
  runserver.sh
Labels: Backend, Code Quality, Infrastructure - LXC

#682 Clean up attrs access among NetCDFData and Model-derived classes
  data/fvcom.py
  data/mercator.py
  data/nearest_grid_point.py
  data/nemo.py
  data/netcdf_data.py
  plotting/drifter.py
  plotting/hovmoller.py
  plotting/observation.py
  plotting/plotter.py
  plotting/scriptGenerator.py
  plotting/stats.py
  plotting/timeseries.py
  routes/api_v1_0.py
  tests/disabled/test_fvcom.py
  tests/test_merc.py
  tests/test_nemo.py
  utils/misc.py
Labels: Code Quality, Python, technical

#683 Database backed observational data.
  data/observational/__init__.py
  data/observational/orm/__init__.py
  data/observational/orm/datatype.py
  data/observational/orm/platform.py
  data/observational/orm/sample.py
  data/observational/orm/station.py
  data/observational/queries.py
  tests/test_observational_queries.py
  tests/testdata/db/datatypes.json
  tests/testdata/db/platform_metadata.json
  tests/testdata/db/platforms.json
  tests/testdata/db/samples.json
  tests/testdata/db/stations.json
Labels: New Feature, Python, technical

#686 Updated the THREDDS URL.
  oceannavigator/frontend/index.html
Labels: Bugfix

#688 Erddap access
  data/netcdf_data.py
  oceannavigator/dataset_config.py
  oceannavigator/datasetconfig.json
  routes/api_v1_0.py
  tests/test_api_v_1_0.py
  tests/test_dataset_config.py
  tests/test_netcdf_data.py
  tests/testdata/datasetconfigpatch.json
Labels: New Feature, Python, enhancement, technical

#689 Add 'chunks' parameter to open_mfdataset.
  data/netcdf_data.py
Labels: Performance, Python, technical

#692 Add salishseacast biology
  oceannavigator/datasetconfig.json
  plotting/colormap.py
  routes/api_v1_0.py
  tests/disabled/test_routes.py
  tests/test_api_v_1_0.py
  tests/test_colormap.py
Labels: Code Quality, Data/Pipelines, New Feature

#687 Flesh out support for timeseries data.
  data/calculated_parser/functions.py
  data/fvcom.py
  data/mercator.py
  data/model.py
  data/nemo.py
  data/netcdf_data.py
  plotting/hovmoller.py
  plotting/point.py
  plotting/timeseries.py
  plotting/transect.py
  tests/disabled/test_fvcom.py
  tests/test_merc.py
  tests/test_nemo.py
  utils/misc.py
Labels: Bugfix, Code Quality, Python, technical

#699 Add SalishSeaCast biology dataset help config
  oceannavigator/datasetconfig.json
Labels: Bugfix, enhancement

#698 Add SalishSeaCast temperature & salinity dataset config
  oceannavigator/datasetconfig.json
Labels: Data/Pipelines, enhancement

#697 Change to use SalishSeaCast geo-ref stored on /data for ssh dataset
  oceannavigator/datasetconfig.json
Labels: Bugfix, Data/Pipelines

#695 Fix typo
  data/calculated_parser/functions.py
Labels: Bugfix, Python

#696 Tweak open_dataset to ingest multiple variables at once
  data/netcdf_data.py
  data/sqlite_database.py
  tests/test_api_v_1_0.py
  tests/testdata/datasetconfigpatch.json
  tests/testdata/endpoints.json
  tests/testdata/giops_test.nc
Labels: Bugfix, Python

#703 Time Series resample fix
  data/mercator.py
  data/nemo.py
Labels: Bugfix, Python

#705 Observational API
  data/observational/queries.py
  oceannavigator/__init__.py
  oceannavigator/oceannavigator.cfg
  routes/api_v1_0.py
  tests/test_api_v_1_0.py
  tests/testdata/endpoints.json
Labels: New Feature, Python

#704 Ditch Class4 dependency on THREDDS & FTP
  data/class4.py
  oceannavigator/oceannavigator.cfg
  plotting/class4.py
  scripts/generate_class4_list.py
  tests/disabled/test_oceannavigator_cfg.py
Labels: Bugfix, Python
