Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2020-12, with the labels that each got.

#791 Drop unused `pint.UnitRegistry` in `Mercator.depths` & `Nemo.depths` properties
  data/mercator.py
  data/nemo.py
Labels: Performance, Python, technical

#789 Only use open_mfdataset() when there is >1 dataset
  data/netcdf_data.py
Labels: Performance, Python, technical

#792 Get Sentry traces_sample_rate value from environment variable
  oceannavigator/__init__.py
Labels: Bugfix, Performance, Priority: High, Python, technical

#793 Delete unused UnitRegistry imports
  data/mercator.py
  data/nemo.py
Labels: Code Quality, Python

#797 Fix for issue #796 re: class4/models/{class4_id} API endpoint
  data/class4.py
  tests/test_data_class4.py
Labels: Bugfix, Python, technical

#794 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: Code Quality, technical

#779 Zarr data access enabled
  data/netcdf_data.py
  tests/test_netcdf_data.py
Labels: New Feature, Python

#753 Implement Depth Excess acoustic variable
  data/__init__.py
  data/calculated_parser/functions.py
  data/netcdf_data.py
  oceannavigator/dataset_config.py
  plotting/colormap.py
  tests/test_dataset_config.py
Labels: Python, User Requested

#806 Change Class 4 profiles legend to show GIOPS model label from the outset
  plotting/class4.py
Labels: Bugfix, Code Quality, Python
