Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2021-12, with the labels that each got.

#924 Fix subsetting for multiple variables and over time ranges
  data/calculated.py
  data/calculated_parser/functions.py
  data/netcdf_data.py
  oceannavigator/frontend/src/components/AreaWindow.jsx
Labels: Bugfix, Python

#928 Add Werkzeug profiling middleware
  oceannavigator/__init__.py
Labels: Python, Performance

#925 Fix reshaping of calculated variables
  data/calculated.py
Labels: Bugfix, Backend, Python

#926 Fix duplicate API calls across `DatasetSelector` component instances
  oceannavigator/frontend/package.json
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  oceannavigator/frontend/src/components/Defaults.js
  oceannavigator/frontend/src/components/LineWindow.jsx
  oceannavigator/frontend/src/components/Map.jsx
  oceannavigator/frontend/src/components/MapInputs.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
  oceannavigator/frontend/src/components/Range.jsx
  oceannavigator/frontend/src/components/TimePicker.jsx
  oceannavigator/frontend/src/components/lib/SelectBox.jsx
  oceannavigator/frontend/src/images/bar_loader.gif
  oceannavigator/frontend/src/remote/OceanNavigator.js
  oceannavigator/frontend/webpack.config.js
  oceannavigator/frontend/yarn.lock
Labels: Javascript, Performance

#932 Revert "Bump jquery-ui from 1.12.1 to 1.13.0 in /oceannavigator/frontend"
  oceannavigator/frontend/package.json
  oceannavigator/frontend/yarn.lock
Labels: Bugfix, dependencies

#934 Remove erroneous call to `addControl` in Map component
  oceannavigator/frontend/src/components/Map.jsx
Labels: Bugfix, Javascript

#935 Bugfix: Fix reference to non-existant prop in DatasetSelector
  oceannavigator/frontend/src/components/DatasetSelector.jsx
Labels: Bugfix, Javascript
