Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2021-03, with the labels that each got.

#814 Get model class from config instead of "sniffing" dataset dimensions
  data/__init__.py
  data/mercator.py
  data/netcdf_data.py
  oceannavigator/dataset_config.py
  routes/api_v1_0.py
  tests/test_data_open_dataset.py
  tests/test_dataset_config.py
  tests/test_merc.py
  tests/test_netcdf_data.py
  tests/testdata/datasetconfigpatch.json
Labels: Code Quality, Python

#823 Add ONC & STRATOGEM stations to Points menu
  kml/point/ONC_Stations.kml
  kml/point/Offshore_Oil_Operations.kml
  kml/point/STRATOGEM_Stations.kml
Labels: User Requested

#824 Issue/784 816 fixing start date of vm
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
Labels: Javascript

#825 Removed references to 'scale_factor'
  oceannavigator/dataset_config.py
  plotting/hovmoller.py
  plotting/map.py
  plotting/observation.py
  plotting/plotter.py
  plotting/point.py
  plotting/profile.py
  plotting/stats.py
  plotting/stick.py
  plotting/tile.py
  plotting/timeseries.py
  plotting/track.py
  plotting/transect.py
  plotting/ts.py
Labels: Code Quality, Python

#822 Add GeoJSON transformer to data package
  data/transformers/geojson.py
  data/utils.py
  tests/data/transformers/test_geojson.py
  tests/test_data_utils.py
Labels: Python

#817 Add selectbox for choosing bathymetry layer source
  oceannavigator/frontend/src/components/Map.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/Options.jsx
Labels: Javascript, New Feature, User Requested

#828 Bringing in marshmallow version 3.11.0 from conda-forge.
  config/conda/navigator-spec-file.txt
Labels: Backend, enhancement
