Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2021-09, with the labels that each got.

#899 Upgrading the version of tar from ^2.0.0 to ^4.4.18.
  oceannavigator/frontend/package.json
  oceannavigator/frontend/yarn.lock
Labels: Javascript, Priority: Medium, Security

#900 Update glob-parent to ^5.1.2
  oceannavigator/frontend/package.json
  oceannavigator/frontend/yarn.lock
Labels: Javascript, Priority: Medium, Security

#902 Add updateOptions to AreaWindow props
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
Labels: Bugfix

#903 Fix variable selector in virtual mooring tab
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/ComboBox.jsx
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
Labels: Bugfix

#883 [Major change] Dump `babel` for `typescript`
  oceannavigator/frontend/.babelrc
  oceannavigator/frontend/.jshintrc
  oceannavigator/frontend/package.json
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/Class4Window.jsx
  oceannavigator/frontend/src/components/ComboBox.jsx
  oceannavigator/frontend/src/components/ContourSelector.jsx
  oceannavigator/frontend/src/components/CoordInputPanel.jsx
  oceannavigator/frontend/src/components/CustomPlotLabels.jsx
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  oceannavigator/frontend/src/components/DepthLimit.jsx
  oceannavigator/frontend/src/components/DrifterSelector.jsx
  oceannavigator/frontend/src/components/EnterArea.jsx
  oceannavigator/frontend/src/components/EnterLine.jsx
  oceannavigator/frontend/src/components/EnterPoint.jsx
  oceannavigator/frontend/src/components/ImageSize.jsx
  oceannavigator/frontend/src/components/LineWindow.jsx
  oceannavigator/frontend/src/components/LocationInput.jsx
  oceannavigator/frontend/src/components/Map.jsx
  oceannavigator/frontend/src/components/MapInputs.jsx
  oceannavigator/frontend/src/components/MapToolbar.jsx
  oceannavigator/frontend/src/components/NumberBox.jsx
  oceannavigator/frontend/src/components/ObservationSelector.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/Options.jsx
  oceannavigator/frontend/src/components/Permalink.jsx
  oceannavigator/frontend/src/components/PlotImage.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
  oceannavigator/frontend/src/components/QuiverSelector.jsx
  oceannavigator/frontend/src/components/Range.jsx
  oceannavigator/frontend/src/components/StatsTable.jsx
  oceannavigator/frontend/src/components/TimePicker.jsx
  oceannavigator/frontend/src/components/ToggleLanguage.jsx
  oceannavigator/frontend/src/components/TrackWindow.jsx
  oceannavigator/frontend/src/components/VelocitySelector.jsx
  oceannavigator/frontend/src/components/WarningBar.jsx
  oceannavigator/frontend/src/currentLanguage.js
  oceannavigator/frontend/src/i18n.js
  oceannavigator/frontend/src/index.jsx
  oceannavigator/frontend/tsconfig.json
  oceannavigator/frontend/webpack.config.js
  oceannavigator/frontend/yarn.lock
Labels: technical, Javascript, dependencies

#880 Implement depth cache
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  oceannavigator/frontend/src/components/LineWindow.jsx
  oceannavigator/frontend/src/components/MapInputs.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
  oceannavigator/frontend/src/components/lib/SelectBox.jsx
  oceannavigator/frontend/src/remote/OceanNavigator.js
Labels: technical, Javascript, Performance
