Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2021-11, with the labels that each got.

#920 Restore NC3 Subsetting for Calculated Variables
  data/netcdf_data.py
Labels: Bugfix, Python

#922 Updates to a couple of service scripts
  bin/launch-web-service.sh
  bin/runserver.sh
Labels: Backend

#911 Stop duplicate API calls for Variables dropdown
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/ComboBox.jsx
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  oceannavigator/frontend/src/components/LineWindow.jsx
  oceannavigator/frontend/src/components/Map.jsx
  oceannavigator/frontend/src/components/MapInputs.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/Range.jsx
  oceannavigator/frontend/src/components/lib/SelectBox.jsx
  routes/api_v1_0.py
Labels: Javascript, Performance
