Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2021-07, with the labels that each got.

#853 Refactoring the /generateScript API end-point to receive query params.
  oceannavigator/frontend/src/components/PlotImage.jsx
  routes/api_v1_0.py
Labels: Backend, Bugfix, Javascript, Python

#857 Add schemas to some endpoints
  routes/api_v1_0.py
  routes/schemas/__init__.py
  routes/schemas/depth_schema.py
  routes/schemas/quantum_schema.py
  routes/schemas/timestamps_schema.py
  tests/routes/schemas/test_depth_schema.py
  tests/routes/schemas/test_quantum_schema.py
  tests/routes/schemas/test_timestamps_schema.py
Labels: Python, technical

#858 Fix bug in depth endpoint
  routes/api_v1_0.py
Labels: Bugfix, Python

#859 Exclude unknown fields in TimestampsSchema
  routes/schemas/timestamps_schema.py
Labels: Bugfix, Javascript, Python

#860 Creation of new navigator spec file
  config/conda/navigator-spec-file.txt
Labels: Python

#861 Add schema to generatescript endpoint
  routes/api_v1_0.py
  routes/schemas/__init__.py
  routes/schemas/generate_script_schema.py
  tests/routes/schemas/test_generate_script_schema.py
  tests/routes/test_api_v_1_0_generatescript.py
  tests/test_api_v_1_0.py
Labels: Code Quality, Python

#862 Update DatasetSelector.jsx
  oceannavigator/frontend/src/components/DatasetSelector.jsx
Labels: Javascript

#865 Update `webpack` to latest v4
  oceannavigator/frontend/package.json
  oceannavigator/frontend/webpack.config.js
  oceannavigator/frontend/yarn.lock
Labels: Javascript, dependencies, technical

#867 Remove unused JS packages
  oceannavigator/frontend/package.json
  oceannavigator/frontend/yarn.lock
Labels: Javascript, dependencies

#868 Use axios for fetching timestamps and variables in OceanNavigator component
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/remote/OceanNavigator.js
Labels: Javascript, technical

#869 Fix linting for SelectBox component
  oceannavigator/frontend/src/components/lib/SelectBox.jsx
Labels: Javascript
