Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2021-06, with the labels that each got.

#848 Modified the interpolation function to return a masked array when "Nearest Neighbour" is selected
  data/netcdf_data.py
Labels: Bug, Python

#849 Add bearing to magnitude timeseries csv and ensure timeseries data is ordered
  data/sqlite_database.py
  plotting/timeseries.py
Labels: Bugfix, Python

#850 Select JS packages have been updated due to security alerts
  oceannavigator/frontend/package.json
  oceannavigator/frontend/yarn.lock
Labels: Javascript, Priority: High, Security

#851 Implement bearing calculated variable
  data/calculated_parser/functions.py
  plotting/colormap.py
Labels: Python, enhancement

#852 Creation of new navigator spec file
  config/conda/navigator-spec-file.txt
Labels: Backend, enhancement
