Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2021-08, with the labels that each got.

#871 Update `ol` from 6.5.0 to latest 6.6.1 & conditionally force a refresh of map's vector source
  oceannavigator/frontend/package.json
  oceannavigator/frontend/src/components/Map.jsx
  oceannavigator/frontend/yarn.lock
Labels: Bugfix, Javascript, dependencies

#872 Improve some crappy JS error messages
  oceannavigator/frontend/src/components/MapToolbar.jsx
Labels: Code Quality, Javascript

#874 Switch remote calls for lines, points, areas to axios
  oceannavigator/frontend/src/components/MapToolbar.jsx
  oceannavigator/frontend/src/remote/OceanNavigator.js
Labels: Javascript, technical

#875 Explicitly set projection of hi-res bathy layer in Map `componentDidUpdate`
  oceannavigator/frontend/src/components/Map.jsx
Labels: Bugfix, Javascript

#877 Fix images loaded via webpack failing to load
  oceannavigator/frontend/src/components/Map.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/PlotImage.jsx
  oceannavigator/frontend/src/components/fail.js
Labels: Javascript, Bug

#878 Add axios `getdepthspromise`
  oceannavigator/frontend/src/remote/OceanNavigator.js
Labels: Javascript

#876 Update proj4 from v2.4.3 to v2.7.5
  oceannavigator/frontend/package.json
  oceannavigator/frontend/yarn.lock
Labels: Javascript, dependencies

#879 Move Icon component to lib/
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/ComboBox.jsx
  oceannavigator/frontend/src/components/CustomPlotLabels.jsx
  oceannavigator/frontend/src/components/MapInputs.jsx
  oceannavigator/frontend/src/components/MapToolbar.jsx
  oceannavigator/frontend/src/components/NumberBox.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/Options.jsx
  oceannavigator/frontend/src/components/Permalink.jsx
  oceannavigator/frontend/src/components/PlotImage.jsx
  oceannavigator/frontend/src/components/TimePicker.jsx
  oceannavigator/frontend/src/components/lib/Icon.jsx
Labels: Javascript, Code Quality

#873 Fix subsetting of predefined areas
  data/netcdf_data.py
  oceannavigator/frontend/src/components/AreaWindow.jsx
  routes/api_v1_0.py
  routes/schemas/generate_script_schema.py
Labels: Python

#884 Re-enable main map quiver arrows
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  oceannavigator/frontend/src/components/LineWindow.jsx
  oceannavigator/frontend/src/components/MapInputs.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  routes/api_v1_0.py
Labels: Bugfix, New Feature, Javascript, Python, Erica Wishlist

#891 Add script to pre-gen tiles
  scripts/pregen_tiles.py
Labels: technical, Python, Performance
