Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2022-04, with the labels that each got.

#1001 Add `/api/dump-heap-memory` endpoint
  routes/api_v1_0.py
Labels: Python, Performance

#1002 Cannot generate bathymetry tiles for polar projections #999
  oceannavigator/frontend/src/components/Map.jsx
Labels: Javascript, Python, Bug

#998 Draw & plot multiple points on click
  oceannavigator/frontend/src/components/Map.jsx
  oceannavigator/frontend/src/components/MapToolbar.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
Labels: New Feature, Javascript, User Requested

#1004 Reduce map preload levels from 7 to 1
  oceannavigator/frontend/src/components/Map.jsx
Labels: Javascript, Performance

#1007 Remove `hashable_lru` decorator from `open_dataset`
  data/__init__.py
  oceannavigator/__init__.py
Labels: Python, Performance

#1005 Replace Basemap with Cartopy
  plotting/basemap.py
  plotting/class4.py
  plotting/hovmoller.py
  plotting/map.py
  plotting/overlays.py
  plotting/profile.py
  plotting/sound.py
  plotting/timeseries.py
  plotting/track.py
  plotting/transect.py
  plotting/ts.py
  plotting/utils.py
Labels: Bugfix, Python, Code Quality

#1010 Update Cartopy resource directory
  plotting/basemap.py
  plotting/utils.py
Labels: Python
