Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2022-11, with the labels that each got.

#1041 Correct Critical Depth and Depth Excess calculations
  data/calculated_parser/functions.py
Labels: Bugfix, Python

#1045 Prevent conflicting Unit/Units variable attributes
  data/netcdf_data.py
  data/transformers/geojson.py
  oceannavigator/dataset_config.py
  plotting/transect.py
  tests/test_dataset_config.py
  tests/testdata/datasetconfigpatch.json
Labels: Bugfix, Python, Data/Pipelines

#1066 Allow entering/importing point lattitude- longitudes values outside [-90, 90] and [-180, 180] range
  oceannavigator/frontend/src/components/MapToolbar.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/lib/CheckBox.jsx
Labels: Javascript, Python, Bug, Priority: Medium

#1070 PSSC TimeSeries Point Plot issue Resolved
  data/calculated_parser/functions.py
Labels: Bugfix, Python, Priority: Medium

#1071 Fixed issue with variable specific interpolation settings from datasetconfig
  data/data.py
  data/netcdf_data.py
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  oceannavigator/frontend/src/components/PlotImage.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
  plotting/timeseries.py
Labels: Bugfix, Javascript, Python

#1074 Fix 'MySQL server has gone away' error with pool recycling
  data/observational/__init__.py
Labels: Bugfix, Python, observations

#1078 Specify quiver variables in datasetconfig
  oceannavigator/dataset_config.py
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  routes/api_v2_0.py
  tests/test_api_v_2_0.py
  tests/test_dataset_config.py
  tests/testdata/datasetconfigpatch.json
Labels: Javascript, Python

#1079 Fix /range API endpoint
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  routes/api_v2_0.py
  tests/test_api_v_2_0.py
Labels: Bugfix, Python

#1080 Plot GDWPS Quivers
  data/calculated_parser/lexer.py
  data/transformers/geojson.py
  oceannavigator/frontend/src/components/Map.jsx
  oceannavigator/frontend/src/images/s111/I0.svg
  oceannavigator/frontend/src/images/s111/I1.svg
  oceannavigator/frontend/src/images/s111/I2.svg
  oceannavigator/frontend/src/images/s111/I3.svg
  oceannavigator/frontend/src/images/s111/I4.svg
  oceannavigator/frontend/src/images/s111/I5.svg
  oceannavigator/frontend/src/images/s111/I6.svg
  oceannavigator/frontend/src/images/s111/I7.svg
  oceannavigator/frontend/src/images/s111/I8.svg
  oceannavigator/frontend/src/images/s111/I9.svg
  routes/api_v2_0.py
  tests/data/transformers/test_geojson.py
Labels: enhancement, Python
