Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2022-06, with the labels that each got.

#1025 Subset panel does not update when dataset is changed within the area window Issue #971
  oceannavigator/frontend/src/components/AreaWindow.jsx
Labels: Bugfix, Javascript

#1026 Add filename pattern to _list_class4_files_slowly
  data/class4.py
Labels: Bugfix

#1029 Adding new packages to the navigator Python virtual env
  config/conda/navigator-spec-file.txt
Labels: enhancement
