Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2022-01, with the labels that each got.

#936 Bugfix: Remove unused function binding in `AreaWindow`
  oceannavigator/frontend/src/components/AreaWindow.jsx
Labels: Bugfix, Javascript

#940 Revive dataset help button
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  oceannavigator/frontend/src/components/lib/SelectBox.jsx
Labels: Bugfix

#941 restore quiver arrows
  routes/api_v1_0.py
Labels: Bugfix, Backend, Python

#930 Fix observation tracks unable to cross intl date line
  routes/api_v1_0.py
Labels: Bugfix, Backend, Python

#937 Implement Go button
  oceannavigator/frontend/src/components/DatasetSelector.jsx
Labels: New Feature, Javascript, User Requested, Erica Wishlist

#953 Limit default time selector range
  oceannavigator/frontend/src/components/DatasetSelector.jsx
Labels: Javascript

#952 Fix `id` of right map dataset selector
  oceannavigator/frontend/src/components/MapInputs.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
Labels: Bugfix, Javascript

#954 prefetch times for DATASET_DEFAULTS
  oceannavigator/frontend/src/components/OceanNavigator.jsx
Labels: Bugfix, Javascript

#955 Basemap bug fixes
  plotting/map.py
Labels: Bugfix, Backend, Python

#956 Fixed for issue 543
  oceannavigator/frontend/src/components/PlotImage.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
  plotting/timeseries.py
  routes/api_v1_0.py
Labels: Javascript, Python, Code Quality

#957 Profiler additions
  scripts/profiling_scripts/api_profiling_config.json
  scripts/profiling_scripts/api_profiling_driver.py
  scripts/profiling_scripts/profiler_readme.md
  scripts/profiling_scripts/run_profiler.sh
Labels: Performance

#958 Change areawindow datasetselector onupdate method
  oceannavigator/frontend/src/components/AreaWindow.jsx
Labels: Bugfix, Javascript
