Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2022-08, with the labels that each got.

#1050 API Script R Subset Implementation- The Process Of FastAPI Migration
  plotting/templates/rSUBSETtemplate.txt
Labels: New Feature, Python, User Requested, Priority: Medium

#1053 Remove Basemap MaskOcean from UI
  config/conda/environment.yml
  config/conda/navigator-spec-file.txt
  plotting/map.py
Labels: Python, Priority: Medium

#1056 Additional contour plot issue resolved
  plotting/map.py
Labels: Bugfix, Python, Priority: High

#1057 Rename Old Selecbox React Component->CheckBox and Move >lib folder
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/Class4Window.jsx
  oceannavigator/frontend/src/components/ContourSelector.jsx
  oceannavigator/frontend/src/components/LineWindow.jsx
  oceannavigator/frontend/src/components/MapInputs.jsx
  oceannavigator/frontend/src/components/Options.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
  oceannavigator/frontend/src/components/SubsetPanel.jsx
  oceannavigator/frontend/src/components/TrackWindow.jsx
  oceannavigator/frontend/src/components/VelocitySelector.jsx
  oceannavigator/frontend/src/components/lib/CheckBox.jsx
Labels: Javascript, Priority: Medium, Code Quality

#1060 Disable SSL verification in python scripts
  scripts/pregen_tiles.py
  scripts/profiling_scripts/api_profiling_driver.py
Labels: Bugfix, Python

#1052 Limit the date ranges of class4 calendars
  kml
  oceannavigator/frontend/package.json
  oceannavigator/frontend/src/components/MapToolbar.jsx
  oceannavigator/frontend/yarn.lock
Labels: enhancement, Javascript

#1059 Nested dataset dropdown
  oceannavigator/dataset_config.py
  oceannavigator/frontend/src/components/DatasetDropdown.jsx
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  oceannavigator/frontend/src/stylesheets/components/_DatasetDropdown.scss
  oceannavigator/frontend/src/stylesheets/components/_all.scss
  routes/api_v1_0.py
Labels: enhancement, New Feature, Javascript

#1063 Class4 Data Issue Resolved- Empty Points, Plot Labels, Addition Of Banner
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/WarningBar.jsx
  plotting/class4.py
Labels: Bugfix, Javascript, Python, Priority: High

#1064 Add time dim unit API endpoint or add to dataset payload
  routes/api_v1_0.py
  routes/schemas/__init__.py
  routes/schemas/timedimension_schema.py
Labels: enhancement, Python, Priority: Medium
