Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2022-02, with the labels that each got.

#960 Get area window plot query data from updated props
  oceannavigator/frontend/src/components/AreaWindow.jsx
Labels: Bugfix, Javascript

#959 Use cached quiver variable data
  routes/api_v1_0.py
Labels: Bugfix, Python

#961 API: Enable /data to also return 2D variables
  routes/api_v1_0.py
Labels: Bugfix, Python

#962 Fix great lakes area plots
  plotting/map.py
Labels: Bugfix, Python

#967 Make stride of geojson conversion configurable through datasetconfig
  oceannavigator/dataset_config.py
  routes/api_v1_0.py
Labels: Python

#966 Issue 923
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/DatasetSelector.jsx
Labels: Bugfix, Javascript
