Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2022-05, with the labels that each got.

#1011 Fix R API scripts
  plotting/templates/rCSVtemplate.txt
  plotting/templates/rPLOTtemplate.txt
Labels: Bugfix

#1014 Create dependency-review.yml
  .github/workflows/dependency-review.yml
Labels: Security

#1016 Remove API button from map toolbar
  oceannavigator/frontend/src/components/MapToolbar.jsx
Labels: Javascript

#1018 Handle missing Cartopy resources
  plotting/basemap.py
  plotting/utils.py
Labels: Bugfix, Python, Code Quality

#1009 Add Git Version endpoint to API and Response Header
  .github/workflows/python-tests.yml
  oceannavigator/__init__.py
  routes/api_v1_0.py
Labels: New Feature, Python

#1020 VM Plotting Issue With Multi Point Selection
  plotting/timeseries.py
Labels: Bugfix, Python
