Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2022-07, with the labels that each got.

#1031 Quiver variable restriction on model class
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  routes/api_v1_0.py
Labels: Bugfix, Javascript, Python

#1032 Add "bearing component" in "magwatervel" variable component for multiple quiver variable options in UI
  data/transformers/geojson.py
  oceannavigator/dataset_config.py
  routes/api_v1_0.py
Labels: New Feature, Python

#1033 Subset Panel Time Stamp Update Issue Resolved
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/SubsetPanel.jsx
Labels: Bugfix, Javascript, Bug

#1035 Set up SQLalchemy for FastAPI
  data/netcdf_data.py
  data/observational/__init__.py
  data/observational/orm/datatype.py
  data/observational/orm/platform.py
  data/observational/orm/sample.py
  data/observational/orm/station.py
  data/observational/queries.py
  data/observational/schemas/__init__.py
  data/observational/schemas/datatype_schema.py
  data/observational/schemas/platform_schema.py
  data/observational/schemas/sample_schema.py
  data/observational/schemas/station_schema.py
  oceannavigator/frontend/src/components/Map.jsx
  routes/api_v1_0.py
  runserver.py
  test_fundy.ipynb
Labels: Python, observations

#1015 Add Statistics to Plots and csv Files
  oceannavigator/frontend/src/components/PlotImage.jsx
  plotting/hovmoller.py
  plotting/map.py
  plotting/plotter.py
  plotting/profile.py
  plotting/sound.py
  plotting/tile.py
  plotting/timeseries.py
  plotting/track.py
  plotting/transect.py
  plotting/utils.py
Labels: New Feature, Python, User Requested

#1037 Ensure plot contains data before calculating stats
  plotting/plotter.py
Labels: Bugfix, Python

#1036 Fix transect plotting from entered coordinates
  plotting/utils.py
Labels: Bugfix, Python

#1040 Add in CMEMS Product User Manuas.
  oceannavigator/frontend/data-help/CMEMS-GLO-PUM-001-024.pdf
  oceannavigator/frontend/data-help/CMEMS-GLO-PUM-001-028.pdf
  oceannavigator/frontend/data-help/CMEMS-GLO-PUM-001-030.pdf
Labels: Documentation

#1047 Add Accordion Component for UI Organization
  oceannavigator/frontend/src/components/AreaWindow.jsx
  oceannavigator/frontend/src/components/Class4Window.jsx
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  oceannavigator/frontend/src/components/LineWindow.jsx
  oceannavigator/frontend/src/components/PointWindow.jsx
  oceannavigator/frontend/src/components/TrackWindow.jsx
  oceannavigator/frontend/src/components/lib/Accordion.jsx
  oceannavigator/frontend/src/stylesheets/components/_all.scss
Labels: enhancement, Javascript

#1048 Pathlib Implementation In Ocean Navigator UI - The Process Of FastAPI Migration
  data/class4.py
  data/netcdf_data.py
  oceannavigator/__init__.py
  oceannavigator/dataset_config.py
  plotting/basemap.py
  plotting/colormap.py
  plotting/overlays.py
  routes/api_v1_0.py
  utils/function_profiler.py
  utils/misc.py
Labels: Python, Priority: High, Code Quality
