Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2022-03, with the labels that each got.

#980 New spec and environment files.
  config/conda/environment.yml
  config/conda/navigator-spec-file.txt
Labels: New Feature, Python, Priority: Medium, dependencies

#982 New conda package
  config/conda/environment.yml
  config/conda/navigator-spec-file.txt
Labels: enhancement, Python, Priority: Medium, dependencies

#984 Create Python linting workflow
  .github/workflows/lint_python.yml
  pyproject.toml
Labels: Python, Code Quality

#978 Improve UX for predefined areas
  oceannavigator/frontend/src/components/Map.jsx
Labels: Javascript, User Requested

#988 Fix calculated indexing
  data/calculated.py
Labels: Bugfix, Python

#990 Create action to run python tests
  .github/workflows/python-tests.yml
  README.md
  run_python_tests.sh
  tests/routes/test_api_v_1_0_get_data.py
  tests/test_api_v_1_0.py
  tests/test_data_functions.py
  tests/test_netcdf_data.py
Labels: Python, Code Quality

#991 Fix some python deprecations
  data/netcdf_data.py
  routes/api_v1_0.py
Labels: Python, Code Quality

#993 Fix `cache_timeout` -> `max_age` deprecation warning
  routes/api_v1_0.py
Labels: Python, Code Quality

#994 Remove Qt from conda environment
  config/conda/environment.yml
Labels: Python, dependencies

#996 Remove a bunch of stubbing in python tests
  oceannavigator/__init__.py
  tests/routes/test_api_v_1_0_generatescript.py
  tests/routes/test_api_v_1_0_get_data.py
  tests/test_api_v_1_0.py
  tests/testdata/datasetconfigpatch.json
Labels: Python, Code Quality

#997 [Bugfix] Ensure int is returned in `NetCDFData#timestamp_to_time_index`
  data/netcdf_data.py
  routes/api_v1_0.py
  tests/routes/test_api_v_1_0_get_data.py
  tests/testdata/datasetconfigpatch.json
Labels: Bugfix, Python
