Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2024-09, with the labels that each got.

#1157 Transect profile
  oceannavigator/frontend/src/components/LineWindow.jsx
  oceannavigator/frontend/src/components/MainMap.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/PlotImage.jsx
  oceannavigator/frontend/src/stylesheets/components/_LineWindow.scss
  plotting/transect.py
Labels: New Feature, Javascript, Python, User Requested

#1137 CMEMS observations scripts
  config/conda/environment.yml
  config/conda/navigator-spec-file.txt
  oceannavigator/frontend/src/components/TrackWindow.jsx
  scripts/data_importers/cmems_argo.py
  scripts/data_importers/cmems_ctd.py
  scripts/data_importers/cmems_drifter.py
  scripts/data_importers/cmems_glider.py
  scripts/data_importers/cmems_nafc_ctd.py
  scripts/data_importers/init_cmems_obs.py
  scripts/data_importers/sync_cmems_obs.py
Labels: Python, Data/Pipelines

#1165 Add ONav Lite link to landing page
  oceannavigator/frontend/index.html
Labels: enhancement

#1168 Fix obs point, track, and plot endpoint issues
  data/observational/orm/station.py
  oceannavigator/frontend/src/components/ObservationSelector.jsx
  oceannavigator/frontend/src/components/TrackWindow.jsx
  plotting/track.py
  routes/api_v2_0.py
Labels: Bugfix, Javascript, Python
