Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2024-02, with the labels that each got.

#1110 Optimize Observation Database Queries
  data/observational/queries.py
Labels: enhancement, Python, observations

#1116 Link button fix
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  oceannavigator/frontend/src/components/MapInputs.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/components/ScaleViewer.jsx
Labels: Bugfix, Javascript

#1120 Fix Colormap Range "Auto" Function
  plotting/utils.py
Labels: Bugfix, Python

#1121 Fix EnterCoordsWindow crash
  oceannavigator/frontend/src/components/EnterCoordsWindow.jsx
Labels: Bugfix, Javascript

#1119 area plot crash fix
  oceannavigator/frontend/src/components/ComboBox.jsx
Labels: Bugfix

#1117 Seawater to gsw
  data/calculated_parser/functions.py
  plotting/sound.py
  scripts/data_importers/argo.py
  scripts/data_importers/glider.py
  scripts/data_importers/nafc_ctd.py
  scripts/data_importers/seal.py
  scripts/pfile.py
Labels: Bugfix, Python

#1125 Limit points in timeseries plot
  data/netcdf_data.py
Labels: enhancement, Bugfix, Python
