Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2024-01, with the labels that each got.

#1100 Fix Linear Threshold feature
  oceannavigator/frontend/src/components/LineWindow.jsx
  oceannavigator/frontend/src/components/NumberBox.jsx
Labels: Bugfix, Javascript

#1103 Fix NetCDF3 NC Subsetting
  data/netcdf_data.py
Labels: Bugfix, Python, Priority: High

#1104 Add Hide Data Layer button to MapInputs panel
  oceannavigator/frontend/src/components/MainMap.jsx
  oceannavigator/frontend/src/components/MapInputs.jsx
  oceannavigator/frontend/src/components/OceanNavigator.jsx
  oceannavigator/frontend/src/stylesheets/components/_MapInputs.scss
  oceannavigator/translations/fr.json
Labels: enhancement, Javascript, User Requested

#1109 Upgrade to Python 3.12
  config/conda/environment.yml
  config/conda/navigator-spec-file.txt
  data/calculated_parser/functions.py
  data/netcdf_data.py
  data/observational/__init__.py
  data/observational/schemas/datatype_schema.py
  data/observational/schemas/platform_schema.py
  data/observational/schemas/sample_schema.py
  data/observational/schemas/station_schema.py
  oceannavigator/__init__.py
  oceannavigator/frontend/index.html
  oceannavigator/settings.py
  plotting/map.py
  plotting/overlays.py
  plotting/tile.py
  routes/api_v2_0.py
  scripts/profiling_scripts/api_profiling_driver.py
  tests/test_api_v_2_0.py
Labels: enhancement, Python, Code Quality

#1113 Seawater to gsw
  config/conda/environment.yml
  config/conda/navigator-spec-file.txt
  data/calculated_parser/functions.py
  plotting/sound.py
  plotting/ts.py
  scripts/data_importers/argo.py
  scripts/data_importers/glider.py
  scripts/data_importers/nafc_ctd.py
  scripts/data_importers/seal.py
  scripts/pfile.py
Labels: Python, Code Quality

#1114 Python api scripts fix
  plotting/scriptGenerator.py
  plotting/templates/python_csv_template.txt
  plotting/templates/python_plot_template.txt
Labels: Bugfix, Python

#1115 Auto selector bug
  oceannavigator/frontend/src/components/AxisRange.jsx
Labels: Bugfix, Javascript
