Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2024-03, with the labels that each got.

#1124 fixed slicing for netcdf subset
  data/netcdf_data.py
Labels: Bugfix, Python

#1126 'Dataset Dropdown covers Variable Selector for some datasets' fix
  oceannavigator/frontend/src/stylesheets/components/_DatasetDropdown.scss
Labels: Bugfix

#1134 include quiver when updating map from mountedDataset
  oceannavigator/frontend/src/components/DatasetSelector.jsx
Labels: Bugfix

#1128 Cmems data_importers scripts
  scripts/data_importers/cmems_argo.py
  scripts/data_importers/cmems_drifter.py
  scripts/data_importers/cmems_glider.py
  scripts/data_importers/cmems_nafc_ctd.py
Labels: enhancement, Python
