Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2025-07, with the labels that each got.

#1210 added a smooth transition at zoom level 7
  oceannavigator/frontend/src/components/Map/Map.jsx
  oceannavigator/frontend/src/components/Map/utils.js
Labels: Bugfix, Javascript, Priority: Medium

#1213 land data visible around 180 and resolution criteria fixed
  plotting/basemap.py
Labels: enhancement, Python, Bug, User Requested, Priority: Medium, Code Quality

#1220 Fix polar area plots
  plotting/basemap.py
  plotting/map.py
Labels: Bugfix, Python
