Repository DFO-Ocean-Navigator/Ocean-Data-Map-Project, pull requests merged in 2025-08, with the labels that each got.

#1212 Perimeter Selector
  oceannavigator/frontend/src/components/Map/Map.jsx
  oceannavigator/frontend/src/components/Map/utils.js
Labels: enhancement, Javascript, User Requested, Priority: Low, css

#1231 Improve drawing of land geometries in area plots
  plotting/map.py
Labels: Bugfix, Python, Code Quality

#1218 Improved annotation functionality
  oceannavigator/frontend/src/components/AnnotationButton.jsx
  oceannavigator/frontend/src/components/AnnotationTextWindow.jsx
  oceannavigator/frontend/src/components/Map/AnnotationOverlay.js
  oceannavigator/frontend/src/components/Map/Map.jsx
  oceannavigator/frontend/src/components/Map/utils.js
  oceannavigator/frontend/src/stylesheets/components/_AnnotationButton.scss
  oceannavigator/frontend/src/stylesheets/components/_AnnotationOverlay.scss
  oceannavigator/frontend/src/stylesheets/components/_all.scss
Labels: enhancement, Javascript, User Requested, Priority: Medium, css

#1221 props destructuring
  oceannavigator/frontend/src/components/DatasetSelector.jsx
  oceannavigator/frontend/webpack.config.js
Labels: enhancement, Javascript, Priority: Medium

#1233 Remove mapSettings from DatasetSelector component
  oceannavigator/frontend/src/components/DatasetSelector.jsx
Labels: Bugfix, Javascript, Code Quality
